from .meteo_france import DailyMeteoFrance
from .dwd import DailyDwd
from .flood import DailyFlood
from .forecast import DailyForecast
from .gem import DailyGem
from .gfs import DailyGfs
from .historical import DailyHistorical
from .jma import DailyJma
from .marine import DailyMarine
