from .air_quality import HourlyAirQuality
from .dwd import HourlyDwd
from .ecmwf import HourlyEcmwf
from .forecast import HourlyForecast
from .gem import HourlyGem
from .gfs import HourlyGfs
from .historical import HourlyHistorical
from .jma import HourlyJma
from .marine import HourlyMarine
from .meteo_france import HourlyMeteoFrance
from .metno import HourlyMetno